# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qoe8_XWMt0HCPRLxmDeKs5w1HOroROZW
"""

!pip install pymupdf

import fitz
import re

def clean_text(text):
    # Remove numbers, AM/PM, and extra whitespace, and then return the cleaned text
    text = re.sub(r'\bAM\b|\bPM\b', '', text, flags=re.IGNORECASE)  # Remove AM/PM
    text = re.sub(r'\d+', '', text)  # Remove numbers
    text = re.sub(r'\s+', ' ', text)  # Replace multiple spaces with single space
    return text.strip()

def is_similar(header_footer_1, header_footer_2):
    cleaned_1 = clean_text(header_footer_1)
    cleaned_2 = clean_text(header_footer_2)
    return cleaned_1 == cleaned_2, cleaned_1, cleaned_2

def identify_header_footer(blocks):
    if blocks:
        header = blocks[0][4].strip()
        footer = blocks[-1][4].strip()
        return header, footer
    return "", ""

def extract_text_blocks(pdf_path):
    doc = fitz.open(pdf_path)
    pages_text_blocks = []
    for page in doc:
        blocks = page.get_text("blocks")
        blocks.sort(key=lambda block: block[1])  # Sort blocks by their vertical position
        pages_text_blocks.append(blocks)
    doc.close()
    return pages_text_blocks

def print_differences_and_update(new, old, page_num, type):
    similar, cleaned_new, cleaned_old = is_similar(new, old)
    if not similar:
        print(f"Page {page_num} has a different {type}:")
        # print(f"   Previous {type}: {cleaned_old}")
        print(f"   Current {type}: {cleaned_new}")
    return cleaned_new

def print_header_footer_first_two_pages_and_differences(pdf_path):
    pages_text_blocks = extract_text_blocks(pdf_path)
    previous_header, previous_footer = "", ""

    for i, blocks in enumerate(pages_text_blocks):
        header, footer = identify_header_footer(blocks)

        if i == 1:

            previous_header, previous_footer = header, footer
            print(f"Page {i+1} Header:", header)
            print(f"Page {i+1} Footer:", footer)
            continue


        previous_header = print_differences_and_update(header, previous_header, i+1, "header")
        previous_footer = print_differences_and_update(footer, previous_footer, i+1, "footer")

print_header_footer_first_two_pages_and_differences(pdf_path)